services:
  - type: web
    name: shopify-backend
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: SHOPIFY_API_KEY
        value: cdf87a3ffcdba61997ad6ae74865e2ea
      - key: SHOPIFY_API_SECRET
        value: 2767bf69d963000b4a4fcc90e603710f
      - key: SHOPIFY_ACCESS_TOKEN
        value: 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
      - key: SHOPIFY_SHOP
        value: new-trial-store-services.myshopify.com
